package com.abc.bank.repository;
/**
 * @Author 982933616
 * @create 2019/6/27 9:02
 */
import com.abc.bank.pojo.AccountCurrency;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface AccountCurrencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_currency
     *
     * @mbg.generated
     */
    /**
     * 插入新货币金额
     *
     * @param record
     * @return
     */
    int insert(AccountCurrency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_currency
     *
     * @mbg.generated
     */
    /**
     * insertselective
     *
     * @param record
     * @return
     */
    int insertSelective(AccountCurrency record);

    /**
     * 根据cardid查询
     * @param accountCurrency
     * @return
     */
    AccountCurrency selectByPrimaryKey(AccountCurrency accountCurrency);

    /**
     * 更新外币余额
     * @param accountCurrency
     * @return
     */
    int updateByPrimaryKey(AccountCurrency accountCurrency);
}