package com.abc.bank.Repository;

import com.abc.bank.pojo.AccountCurrency;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface AccountCurrencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_currency
     *
     * @mbg.generated
     */
    int insert(AccountCurrency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_currency
     *
     * @mbg.generated
     */
    int insertSelective(AccountCurrency record);
}