package com.abc.bank.Repository;

import com.abc.bank.pojo.CardInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface CardInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbg.generated
     */
    int insert(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbg.generated
     */
    int insertSelective(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbg.generated
     */
    CardInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CardInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table card_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CardInfo record);
}