package com.abc.bank.repository;

import com.abc.bank.pojo.Users;
import org.apache.ibatis.annotations.Mapper;
/**
 * @Author 982933616
 * @create 2019/6/27 9:02
 */
@Mapper
public interface UsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    /**
     * 根据身份证号删除用户
     * @param identify
     * @return
     */
    int deleteByPrimaryKey(String identify);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    /**
     * 插入新用户
     * @param record
     * @return
     */
    int insert(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    /**
     * 插入
     * @param record
     * @return
     */
    int insertSelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    /**
     * 根据身份证号查找用户
     * @param identify
     * @return
     */
    Users selectByPrimaryKey(String identify);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    /**
     * 更新
     * @param record
     * @return
     */
    int updateByPrimaryKeySelective(Users record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbg.generated
     */
    /**
     * 更新用户信息
     * @param record
     * @return
     */
    int updateByPrimaryKey(Users record);
}