package com.abc.bank.pojo;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table bill
 */
public class Bill implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.CardID
     *
     * @mbg.generated
     */
    private String cardID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.AffairType
     *
     * @mbg.generated
     */
    private String affairType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.TradeTime
     *
     * @mbg.generated
     */
    private String tradeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill.TradeBalance
     *
     * @mbg.generated
     */
    private String tradeBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bill
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.CardID
     *
     * @return the value of bill.CardID
     *
     * @mbg.generated
     */
    public String getCardID() {
        return cardID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.CardID
     *
     * @param cardID the value for bill.CardID
     *
     * @mbg.generated
     */
    public void setCardID(String cardID) {
        this.cardID = cardID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.AffairType
     *
     * @return the value of bill.AffairType
     *
     * @mbg.generated
     */
    public String getAffairType() {
        return affairType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.AffairType
     *
     * @param affairType the value for bill.AffairType
     *
     * @mbg.generated
     */
    public void setAffairType(String affairType) {
        this.affairType = affairType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.TradeTime
     *
     * @return the value of bill.TradeTime
     *
     * @mbg.generated
     */
    public String getTradeTime() {
        return tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.TradeTime
     *
     * @param tradeTime the value for bill.TradeTime
     *
     * @mbg.generated
     */
    public void setTradeTime(String tradeTime) {
        this.tradeTime = tradeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill.TradeBalance
     *
     * @return the value of bill.TradeBalance
     *
     * @mbg.generated
     */
    public String getTradeBalance() {
        return tradeBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill.TradeBalance
     *
     * @param tradeBalance the value for bill.TradeBalance
     *
     * @mbg.generated
     */
    public void setTradeBalance(String tradeBalance) {
        this.tradeBalance = tradeBalance;
    }

    @Override
    public String toString() {
        return "Bill{" +
                "cardID='" + cardID + '\'' +
                ", affairType='" + affairType + '\'' +
                ", tradeTime='" + tradeTime + '\'' +
                ", tradeBalance='" + tradeBalance + '\'' +
                '}';
    }
}